name: Build

env:
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

on:
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/build.yml"
      - "CMakeLists.txt"
      - "cmake/*.cmake"
      - "src/**/*.cpp"
      - "src/**/*.h"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/build.yml"
      - "CMakeLists.txt"
      - "cmake/*.cmake"
      - "src/**/*.cpp"
      - "src/**/*.h"

jobs:
  linux-build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: "recursive"
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.10.0"
          target: "desktop"
          arch: "linux_gcc_64"
          modules: "qtcharts"
      - name: Install Build Dependencies
        run: |
          echo Installing CMake...
          sudo apt install cmake -y
          echo Installing automake...
          sudo apt install autoconf autoconf-archive automake libtool
      - name: Prepare CMake
        run: |
          cmake -S . -B build --preset=linux-gcc
      - name: Build Using CMake
        run: |
          cmake --build build --preset=linux-gcc
      - name: Run Unit Tests
        run: |
          ctest --output-on-failure --test-dir build/test

  windows-build:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: "recursive"
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.10.0"
          target: "desktop"
          arch: "win64_msvc2022_64"
          modules: "qtcharts"
      - uses: ilammy/msvc-dev-cmd@v1.13.0
      - name: Prepare CMake
        run: |
          cmake -S . -B build --preset=windows-msvc
      - name: Build Using CMake
        run: |
          cmake --build build --preset=windows-msvc
      - name: Run Unit Tests
        run: |
          ctest --output-on-failure --test-dir build/test
