name: Build

on:
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/build.yml"
      - "CMakeLists.txt"
      - "cmake/*.cmake"
      - "src/**/*.cpp"
      - "src/**/*.h"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/build.yml"
      - "CMakeLists.txt"
      - "cmake/*.cmake"
      - "src/**/*.cpp"
      - "src/**/*.h"

jobs:
  linux-build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.10.0"
          target: "desktop"
          arch: "linux_gcc_64"
      - name: Install Build Dependencies
        run: |
          echo Installing CMake...
          sudo apt install cmake -y
          echo Installing GR dependencies...
          sudo apt install libjpeg9-dev libpng-dev zlib1g-dev libqhull-dev libcairo2-dev
          sudo apt install libxt6 libxrender1 libxext6 libglx-mesa0 libqt6widgets6 -y
      - name: Run CMake and Build
        run: |
          cmake -S . -B build
          cmake --build build

  windows-build:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: "Install GR: Clone"
        uses: actions/checkout@v5
        with:
          repository: "sciapp/gr"
          ref: "v0.73.24"
      - name: "Install GR: Make and Install"
        run: |
          cmake -S . -B build
          cmake --build build
          cmake --install build
      - uses: actions/checkout@v5
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.10.0"
          target: "desktop"
          arch: "win64_msvc2022_64"
      - name: Run CMake and Build
        run: |
          cmake -S . -B build
          cmake --build build
